version: "3.7"
services:
  userino-ui:
    container_name: userino-ui
    build: .
#    network_mode: "host"
    ports:
      - 7300:7300
    environment:
      PORT: 7300
    networks:
      - app-services


networks:
  app-services:
    name: app-services
    external: true
