version: "3.7"
services:
  userino-server:
    container_name: userino-ui
    build: .
#    network_mode: "host"
    ports:
      - 4001:4001
    environment:
      REDIS_HOST: redis://host.docker.internal:6379
    networks:
      - app-services


networks:
  app-services:
    name: app-services
    external: true
